// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// A utility class for extracting text from various document formats.
///
/// The [Extractor] class provides methods to extract text content from
/// different file types including PDF, DOCX, and CSV files. It automatically
/// detects the file type and uses the appropriate extraction method.
class Extractor {
  /// Creates a new [Extractor] instance.
  ///
  /// The constructor creates an instance of the extractor utility class.
  /// All methods in this class are static, so you typically don't need
  /// to create an instance to use the extraction functionality.
  const Extractor();

  /// Extracts text from a document file.
  ///
  /// This method automatically detects the file type based on the file at [path]
  /// and extracts text using the appropriate method (PDF OCR, DOCX parsing, or CSV parsing).
  ///
  /// Returns the extracted text as a [String], or `null` if extraction fails
  /// or the file type is not supported.
  ///
  /// Supported file types:
  /// - PDF files (application/pdf)
  /// - DOCX files (application/vnd.openxmlformats-officedocument.wordprocessingml.document)
  /// - CSV files (.csv extension)
  static Future<String?> extract({required String path}) =>
      RustLib.instance.api.crateApiExtractExtractorExtract(path: path);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Extractor && runtimeType == other.runtimeType;
}
