name: pdf_ocr
description: "A Flutter/Dart plugin for extracting text from PDF files using native Rust-powered OCR for fast and accurate results. Ideal for applications that need to process and analyze PDF documents on mobile and desktop platforms."
version: 1.1.1
homepage: https://kadasolutions.ch/
repository: https://github.com/kadasolutions/pdf_ocr

environment:
  sdk: ^3.5.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.11.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  ffi: ^2.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
