[package]
name = "pdf_ocr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.86"
docx-rs = "0.4.17"
flutter_rust_bridge = "=2.3.0"
infer = "0.16.0"
pdfium-render = "0.8.24"
