// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `get_text`, `get_text`

Future<String> extractDocx({required String path}) =>
    RustLib.instance.api.crateApiExtractDocxExtractorExtractDocx(path: path);

abstract class GetText {
  Future<String?> getText();
}
